# Para usar esta macro hay que cambiar el SteppingActiong para la Edep gammas
#
/control/verbose 2
/run/verbose 2
#
#TODAS las mediciones son para el detector grande 1000 Lts
/run/initialize
/gps/particle gamma
#z = 16.5 cm para GRANDE   /  -19 cm para CHICO
#Distancia S-D = 39 cm -> -48-39 = -87 cm
#Distancia S-D = 133 cm -> -48-133 = -181 cm IAEA
/gps/pos/type Point
/gps/pos/centre -87.0 0.0 16.5 cm
/gps/direction 1 0 0
/gps/energy 661.66 keV

/analysis/setFileName Cs137_Tgrande_39cm_1_5M
#/analysis/h1/setAscii 0
#/analysis/h1/setAscii 1
/analysis/h1/setAscii 2
/analysis/h1/setAscii 3
/analysis/h1/setAscii 4
/analysis/h1/setAscii 5
/analysis/h1/setAscii 6
/analysis/h1/setAscii 7
/analysis/h1/setAscii 8
#
#/analysis/h1/set 0  11      0  11 MeV	#E_o       +/- 10 keV
#/analysis/h1/set 1  1000   -50  50 cm	#nCaptureX +/- 0.1 cm
/analysis/h1/set 2  1000   -50  50 cm	#gEdepX    +/- 0.1 cm
/analysis/h1/set 3  25000   0  25 MeV	#gamma     +/- 1 keV
/analysis/h1/set 4  10000   0  100 MeV	#neutron   +/- 10 keV
/analysis/h1/set 5  25000   0  25 MeV	#electon   +/- 1 keV
/analysis/h1/set 6  1200    0  1200	#fotones
/analysis/h1/set 7  100     0  2500 ns	#LocalTime +/-25ns
/analysis/h1/set 8  400     0  10000 ns	#PMT_time  +/-25ns
#
/run/printProgress 25000

/run/beamOn 1500000

#/tracking/verbose 1
