#
/control/verbose 2
/run/verbose 2
#
#
/run/initialize
#16.5 cm para grande
/gps/particle neutron
#-19 cm para chico
/gps/pos/type Point
#/gps/pos/centre -87.0 0.0 16.5 cm
#/gps/direction 1 0 0
/gps/pos/centre 0.0 0.0 83.0 cm
/gps/direction 0 0 -1
/gps/energy 500 MeV

/analysis/setFileName Colimado_Tgrande_39cm_250kn_500MeV_Z_MT
/analysis/h1/setAscii 1
/analysis/h1/setAscii 2
/analysis/h1/setAscii 3
/analysis/h1/setAscii 4
/analysis/h1/setAscii 5
/analysis/h1/setAscii 6
/analysis/h1/setAscii 7
/analysis/h1/setAscii 8
#
/analysis/h1/set 1  1100    0  11 MeV	#E_o    +/- 10 keV
/analysis/h1/set 2  1000   -50  50 cm	#Capture Z
/analysis/h1/set 3  1000   -50  50 cm	#Edep z
/analysis/h1/set 4  20000   0  20 MeV	#gamma  +/- 1 keV
/analysis/h1/set 5  50000   0  50 MeV	#neutron
/analysis/h1/set 6  20000   0  20 MeV	#electon
/analysis/h1/set 7  500     0  500 	#fotones
/analysis/h1/set 8  20      0  500 ns	#LocalTime
#
/run/printProgress 50000

/run/beamOn 250000

#/tracking/verbose 1
