# $Id$
#
# Macro file for "Hadr03.cc"
# (can be run in batch, without graphic)
#
/control/verbose 0
/run/verbose 2   # cuts
#
###/testhadr/det/setIsotopeMat B10 5 10 2.46 g/cm3
/testhadr/det/setMat G4_WATER
/testhadr/det/setSize 1000 m
#
/run/initialize
#
/gun/particle neutron
/gun/energy 0.1 MeV
#
#/process/list
#/process/inactivate hadElastic
#
/analysis/h1/setAscii 2
/analysis/h1/setAscii 3
/analysis/h1/setAscii 4
/analysis/h1/setAscii 5
/analysis/h1/setAscii 6
/analysis/h1/setAscii 7
/analysis/h1/setAscii 10
/analysis/h1/setAscii 12
#
/analysis/setFileName Vol_inf_100keV_1e6n
/analysis/h1/set 2  12000  0. 12 MeV	#gamma
/analysis/h1/set 3  10000  0. 10 MeV	#neutron
/analysis/h1/set 4  15000  0. 15 MeV	#proton
/analysis/h1/set 5  12000  0. 12 MeV	#deuterons
/analysis/h1/set 6  16000  0. 16 MeV	#alpha
/analysis/h1/set 7  10000  0. 10 MeV	#nuclei
/analysis/h1/set 10 15000  0. 15 MeV	#Q
/analysis/h1/set 12 240   0  240 none   #A
#
/run/printProgress 200000
#
/run/beamOn 1000000
#
#/control/execute vis.mac
#/control/execute hadr03_mod.in
#
#./Hadr03 hadr03.in > terminal.txt 
