# $Id$
#
# Macro file for "Hadr03.cc"
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
#
##/testhadr/det/setIsotopeMat B10 5 10 2.46 g/cm3
/testhadr/det/setMat G4_WATER
/testhadr/det/setSize 1000 m
#
/run/initialize
#
/gps/particle neutron
/gps/pos/type Point
/gps/pos/centre 0.0 0. 0. cm
/gps/direction 1 0 0
/gps/energy 15 MeV
#
/process/list
#/process/inactivate hadElastic
#
/analysis/setFileName Cubo_infinito_15MeV_500k
/analysis/h1/setAscii 2
/analysis/h1/setAscii 3
/analysis/h1/setAscii 4
/analysis/h1/setAscii 6
/analysis/h1/setAscii 7
/analysis/h1/setAscii 10
/analysis/h1/setAscii 12
#
/analysis/h1/set 2  12000   0.  12 MeV	#gamma     +/- 1 keV
/analysis/h1/set 3  10000   0.  10 MeV	#neutron   +/- 1 keV
/analysis/h1/set 4  1000    0.  10 MeV	#proton    +/- 10 keV
/analysis/h1/set 6  1000    0.  10 MeV	#alpha     +/- 10 keV
/analysis/h1/set 7  1000    0.  10 MeV	#nuclei    +/- 10 keV
/analysis/h1/set 10 5000    0.  5 MeV	#Q
/analysis/h1/set 12 40  1   41  none    #A
#
/run/printProgress 25000
#
/run/beamOn 500000
