# Set tuning parameters
/LAGO_G4/detector/WCDGeometry/WcdRadius 31.5.
/LAGO_G4/detector/WCDGeometry/WcdHeight 60.
/LAGO_G4/detector/WCDGeometry/TyvekThickness 0.05

/LAGO_G4/detector/PMTGeometry/PmtRadius 11.0
/LAGO_G4/detector/PMTGeometry/PmtThickness 0.05
/LAGO_G4/detector/PMTGeometry/PmtOffset 3.85
/LAGO_G4/detector/PMTGeometry/PmtCathThick 0.025

/LAGO_G4/detector/TyvekTunning/TyRefl 0.94
/LAGO_G4/detector/TyvekTunning/TySigAlp .5
/LAGO_G4/detector/TyvekTunning/TySpecLob .75

/LAGO_G4/detector/WaterTunning/abw 0.1
/LAGO_G4/detector/WaterTunning/gac 1.0e-6
